name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libncurses5:i386 \
            libstdc++6:i386 \
            libz1:i386 \
            openjdk-17-jdk

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install cython==0.29.33
          pip install buildozer

      - name: Build with Buildozer
        env:
          ANDROID_ACCEPT_LICENSE: "True"
        run: |
          yes | buildozer -v android debug
